### PR TITLE
Enable binary build - cleanup + initial functionality for GNUmakefile / openssl

### PR DESCRIPTION
**Pull request by hMcLauchlan**
This pr consists of a series of patches to move towards enabling a binary build, and also some documentation fixes. They are labeled accordingly. Please see commit messages for details.

My main concern with these patches is my GNUmakefile changes (4/n, 5/n). I'm not too familiar with best practices in makefiles (or what the enforced standards for this repo are). I took an  educated guess at what a sensible implementation might be based on our previous conversations; please suggest corrections as necessary.

Another issue on my mind is that my changes are very specific in scope (only for GNUmake, only for openssl). For my employer's use case, that is sufficient, but I'm happy to make additional changes to flesh things out if you can provide some pointers as to how I should go about changing cmake/make.

Looking forward to the review, thanks!

### CODE REVIEW

**Comment by jyao1** [comment]
Thank you very much for your contribution.
Some feedback below:

1) Would you please separate different PR for A. "binary build", B. "internal header clean up" and C. "typo" ?
Then I can merge your typo and internal header clean up at first.

2) We are moving toward to use CMAKE (then we can remove makefile and GNUmakefile)
It is burden to maintain 2 copies. We plan to remove makefile and GNUmakefile in the future.

As I mentioned, we are in the process to reorg the code.
You may refer to https://github.com/jyao1/openspdm/blob/reorg/libspdm/CMakeLists.txt

**Comment by hMcLauchlan** [comment]
Hi there,

Thanks for the feedback! In that case, I will make all of my PRs against temp_master still, but make the changes for PR A (binary build) in cmake instead of gnumake. Then at a later time `temp_master` can be rebased into reorg (which I assume is the intention).

Please let me know if I've understood incorrectly what the right course of action is.

**Comment by hMcLauchlan** [comment]
Closing since I'll be modifying this branch

**Comment by jyao1** [comment]
thank you!

**Pull request closed without merging**
